### ISSUE TITLE
Critical: Dialogs view - avatar and initials are not configurable for group and private message

### ISSUE THREAD

**Issue by hagitmer** [Hacknocraft/AppFriendsAndroidCore#1]
The Group Message icon is missing (circle on left side of message row). We need a configurable "avatar icon" layered on top of the image view (otherwise it will scale the icon to take the whole space of the circle which we don't want) 

We also need the initials field to be configurable as it is now hard coded to "LZ" for private conversations.

**Comment by hagitmer** [comment]
We were able to fix it internally so closing this card.

**Comment by HacknocraftDev** [comment]
This issue was moved to Hacknocraft/AppFriendsAndroidCore#2
