### ISSUE TITLE
High: Read receipts on iOS for Android users are incorrect

### ISSUE THREAD

**Issue by hagitmer** [Hacknocraft/AppFriendsAndroidCore#11]
While the Read Receipts screen is not supported on Android, we're expecting that the Read Receipts screen on iOS will be updated with the correct information. 
Meaning, if an Android user read the message, update the Read Receipts status on iOS to say "Seen".

**Comment by hagitmer** [comment]
Hi @laeroah can you please update on the ETA for this? Thank you.

**Comment by laeroah** [comment]
We initially skipped all receipts related features for Android but I guess this one will affect iOS users. will add the read receipts for next release.

**Comment by hagitmer** [comment]
Great, thank you for understanding.

**Comment by hagitmer** [comment]
@laeroah this seems to be broken on the latest release. Hence re-opening this issue.

**Comment by laeroah** [comment]
@hagitmer did you wait for a bit? could take up to 20 seconds for the receipts to be delivered

**Comment by hagitmer** [comment]
@laeroah waited a whole night :) This is also broken on the sample app.

**Comment by laeroah** [comment]
This issue will be fixed by next SDK release, which should happen by Wednesday night.

**Comment by HacknocraftDev** [comment]
This issue was moved to Hacknocraft/AppFriendsAndroidCore#12
