### ISSUE TITLE
Critical: Unread badge is not clearing after reading the new messages in the chat view

### ISSUE THREAD

**Issue by hagitmer** [Hacknocraft/AppFriendsAndroidCore#12]
The unread badge doesn't clear even when returning from the chat view and reading the new messages.
Also, the preview is messed up.
Attached video.
[Image uploaded from iOS.mp4.zip](https://github.com/Hacknocraft/AppFriendsAndroidCore/files/728071/Image.uploaded.from.iOS.mp4.zip)

**Comment by hagitmer** [comment]
Seems to be working on the latest SDK. Closing for now.

**Comment by HacknocraftDev** [comment]
This issue was moved to Hacknocraft/AppFriendsAndroidCore#13
