### ISSUE TITLE
Medium: Keyboard not dismissing when tapping the chat area

### ISSUE THREAD

**Issue by hagitmer** [Hacknocraft/AppFriendsAndroidCore#13]
A standard practice in Android is to dismiss the keyboard once the user taps anywhere else in the screen (so not the keyboard).

Apps the support this behavior: Google Hangouts, Facebook Messenger, and many more.

**Comment by laeroah** [comment]
will add this for the next release.

**Comment by hagitmer** [comment]
seems fixed, thanks!

**Comment by HacknocraftDev** [comment]
This issue was moved to Hacknocraft/AppFriendsAndroidCore#14
