### ISSUE TITLE
High: Dialog titles are not updating between iOS and Android

### ISSUE THREAD

**Issue by hagitmer** [Hacknocraft/AppFriendsAndroidCore#15]
Naming a dialog on iOS doesn't carry over to Android.
For example, I can name a conversation as "AppFriends & GC" on iOS, but it will still appear as "Untitled group, x users" on Android.

**Comment by laeroah** [comment]
should be fixed by 3.0.6 release

**Comment by HacknocraftDev** [comment]
This issue was moved to Hacknocraft/AppFriendsAndroidCore#16
