### ISSUE TITLE
High: unread badge on the dialog view is incorrect when switching devices

### ISSUE THREAD

**Issue by hagitmer** [Hacknocraft/AppFriendsAndroidCore#17]
When logging out from device A and logging in to device B, all the messages are marked as unread.
The expected behavior is that only the messages that are new in between these events are marked as unread instead of all the conversation ever.

**Comment by laeroah** [comment]
The reading status of messages are recorded on the devices right now, so the second device has no way of know which messages are read on the first device. To implement it, we are going to need to remember reading status on the server. 
I will put this request on our development road map for our next version update, which should happen around the third week of Feb.

**Comment by hagitmer** [comment]
@laeroah was this fixed in the 3.1.0 release?

**Comment by hagitmer** [comment]
@laeroah can you please respond to my previous question? Thanks

**Comment by laeroah** [comment]
@hagitmer Sry, I thought we discussed this, but no, it wasn't. We made some progress but it was not complete at the time of the release of the last version. 
Most like this will be included in the mid May release. I will keep you posted.

**Comment by HacknocraftDev** [comment]
This issue was moved to Hacknocraft/afa_test#1
