### ISSUE TITLE
High: dialog ID is missing when deep linking from a push notification

### ISSUE THREAD

**Issue by hagitmer** [Hacknocraft/AppFriendsAndroidCore#18]
@laeroah the dialog ID is missing in Android. 
Also, the dialog ID was available in iOS and got removed (without notifying us).

Can you bring it back for iOS and add it to Android?

**Comment by laeroah** [comment]
@hagitmer sorry, accidentally broke it developing push for android. since their logic is shared. 
Could you try it now? dialog id should now be available on ios and android.

**Comment by hagitmer** [comment]
It's working now on both Android and iOS. Thanks for the prompt response.

**Comment by HacknocraftDev** [comment]
This issue was moved to Hacknocraft/AppFriendsAndroidCore#18
