### ISSUE TITLE
Medium: Can't track message sends

### ISSUE THREAD

**Issue by hagitmer** [Hacknocraft/AppFriendsAndroidCore#19]
We need public access to the send button tap event.  To track successful message sends we need a public callback when a message was sent successfully (similar to what is exposed in iOS)

**Comment by laeroah** [comment]
Ok, will add them

**Comment by laeroah** [comment]
with 3.0.6, you can get callback using:
```
        AppFriends.getInstance().chatService().monitorMessageSendStatus()
                .subscribe(new Subscriber<Message.Type>() {
```
We put some sample code in the public sample app.

**Comment by HacknocraftDev** [comment]
This issue was moved to Hacknocraft/AppFriendsAndroidCore#19
