### ISSUE TITLE
URGENT BLOCKER: AppFriends environment initialization is not configurable

### ISSUE THREAD

**Issue by hagitmer** [Hacknocraft/AppFriendsAndroidCore#20]
Change the init method on the AppFriends class to be able to pass the appID and appSecret in.  Also the AppFriends instance must be able to be re-initialized.

@laeroah note that this issue is preventing us from connecting to our production environment which makes it a release blocker for us. Thanks

**Comment by laeroah** [comment]
@hagitmer hi, the appID and appSecret can be set here:
```
<meta-data
    android:name="me.appfriends.AppID"
    android:value="[your app id here]" />

<meta-data
    android:name="me.appfriends.AppSecret"
    android:value="[your app secret here]" />
```
Document is here: https://github.com/Hacknocraft/AppFriendsAndroidSample
under: *Setting App Key and App Secret*

**Comment by nrschultz** [comment]
@laeroah The issue is that we need to be able to change the environment that we're connecting to at run-time, and that meta-data is unable to be changed at runtime.

**Comment by laeroah** [comment]
@nrschultz Most of the SDK out there like Fabric, Facebook and etc let you set these keys in the manifest. It is pretty standard for Android. You can also have different manifest files for different build configurations, it shouldn't be a problem even if you want to automate with Jenkins. 
Changing environment or appID at run time isn't something we support. It can cause unexpected behaviors to the app that will only confuse your QA and false positive on bugs.
On iOS, you are not suppose to call initialized again after the SDK is already initialized either.

**Comment by hagitmer** [comment]
Hi @laeroah; thanks for the detailed explanation. A few thoughts about our testing process and the logic behind it:
We test the GC app by logging into our staging environment. If we create a different build for staging, we might miss out issues that exist in the production build. So, a basic QA requirement is that the build we test is the build we ship. 
You could make the argument that we can test on production, however this also has unwanted consequences, which the main one is that we will pollute our users data with our internal testing data.

Let me know if that makes sense or if you want to discuss live. Thank you!

**Comment by laeroah** [comment]
ok, I understand, although this is probably the same with most of other SDK you would be using in your app. I have to take a look at our side to see what's the best we can do. Definitely won't be able to make any changes for today's release now, so it has to wait for next week, and we will have more frequent releases next week.
However, I have to make it clear that this is only to facilitate your testing and we will not be testing switching environment on our end for now. Just hope it doesn't generate false positive bugs which end up wasting time for both teams.

**Comment by laeroah** [comment]
added the interface in 3.0.7

**Comment by HacknocraftDev** [comment]
This issue was moved to Hacknocraft/AppFriendsAndroidCore#20
