### ISSUE TITLE
Low: Missing system messages

### ISSUE THREAD

**Issue by hagitmer** [Hacknocraft/AppFriendsAndroidCore#21]
The following system messages are available in iOS:

1. User join the conversation ("Hagit Mer joined this conversation")
2. Conversation rename ("Hagit Mer has renamed the conversation to Coaches")

**Comment by hagitmer** [comment]
Available in the latest SDK hence closing.

**Comment by HacknocraftDev** [comment]
This issue was moved to Hacknocraft/AppFriendsAndroidCore#21
