### ISSUE TITLE
High: shared photos has a 90 degrees rotation to the left

### ISSUE THREAD

**Issue by hagitmer** [Hacknocraft/AppFriendsAndroidCore#23]
See attached photos as shared from Android. Note that the picture has the correct rotation (0 degrees) when shared in iOS, landscape and portrait.
![img_6caa1bd4b0ad-1](https://cloud.githubusercontent.com/assets/21039229/22483707/5db1b594-e7cc-11e6-96bc-09339738d2c4.jpeg)
![img_efb36879819c-1](https://cloud.githubusercontent.com/assets/21039229/22483708/5db967bc-e7cc-11e6-8fe1-acc191600d78.jpeg)

.

**Comment by laeroah** [comment]
This issue will be fixed by next SDK release, which should happen by Wednesday night.

**Comment by HacknocraftDev** [comment]
This issue was moved to Hacknocraft/AppFriendsAndroidCore#23
