### ISSUE TITLE
Critical: No feedback to the user when the message fails to send

### ISSUE THREAD

**Issue by hagitmer** [Hacknocraft/AppFriendsAndroidCore#24]
We should provide some indication to the user when the message hasn't sent due to network or server error.

**Comment by laeroah** [comment]
yeah, we are working on it. Will have an indicator next to the message like iOS. However, we probably won't have the logic to resend the message finished in time.

**Comment by HacknocraftDev** [comment]
This issue was moved to Hacknocraft/AppFriendsAndroidCore#24
