### ISSUE TITLE
High: Tapping a push notification for a 1:1 conversation leads to a blank conversation

### ISSUE THREAD

**Issue by hagitmer** [Hacknocraft/AppFriendsAndroidCore#25]
Note that this only happens for:
1. The first push tapped for a new 1:1 conversation
2. Doesn't happen for the first push of a group conversation

@laeroah I have a video that shows this issue but it's too big to upload to Github. Can send it over slack if that's helpful, let me know.

**Comment by laeroah** [comment]
This issue will be fixed by next SDK release, which should happen by Wednesday night.

**Comment by hagitmer** [comment]
Thanks @laeroah. We also noticed that deep linking for new conversations are opening the play store rather than open the app. Is that the same root cause?

**Comment by laeroah** [comment]
no, I don't think so. We don't have any logic to open play store. The actions triggered by push are completed handled in the app itself.

**Comment by hagitmer** [comment]
Still broken for 1:1 conversations.

**Comment by laeroah** [comment]
released and closing.

**Comment by HacknocraftDev** [comment]
This issue was moved to Hacknocraft/AppFriendsAndroidCore#25
