### ISSUE TITLE
HIGH: 1:1 conversation title (the user's name) disappears when switching devices and renames to "Private Conversation"

### ISSUE THREAD

**Issue by hagitmer** [Hacknocraft/AppFriendsAndroidCore#26]
1. Start a new 1:1 conversation from User A (iOS) to User B (Android)
2. Have "A" logout of the iOS device and onto an Android device
3. The conversation with "B" will appear on the Android device as "Private Conversation" instead of "User B"

**Comment by laeroah** [comment]
This issue will be fixed by next SDK release, which should happen by Wednesday night.

**Comment by laeroah** [comment]
Didn't get to fix today, but will have it next.

**Comment by hagitmer** [comment]
@laeroah this is still broken in 3.0.11. Can you please update on the ETA for the fix? Thanks!

**Comment by laeroah** [comment]
this issue will be resolved with the first push tap issue. 
These two issues actually have similar cause. After switching device, the user you talked to on the other device is not known to this new device yet.

**Comment by laeroah** [comment]
released and closing.

**Comment by HacknocraftDev** [comment]
This issue was moved to Hacknocraft/AppFriendsAndroidCore#26
