### ISSUE TITLE
HIGH: Taking a picture on Samsung S5 running Android 5.0 crashes the app

### ISSUE THREAD

**Issue by hagitmer** [Hacknocraft/AppFriendsAndroidCore#27]

**Comment by laeroah** [comment]
We tried on Samsung S4 Android 5.0.1, it didn't crash. Could you please attach the crash log here?

**Comment by hagitmer** [comment]
[com.gc.android.qa_issue_190_crash_58A355C702A9000123A0E12E2A852E4A_b0a29658897f4ceaab743b77eaed22a1_0_v1.txt](https://github.com/Hacknocraft/AppFriendsAndroidCore/files/778621/com.gc.android.qa_issue_190_crash_58A355C702A9000123A0E12E2A852E4A_b0a29658897f4ceaab743b77eaed22a1_0_v1.txt)

**Comment by laeroah** [comment]
looks like the device ran out of memory? I will investigate if it is caused by something we do with the image.

**Comment by hagitmer** [comment]
Thanks @laeroah

**Comment by mikedw** [comment]
3.1.x has support for image processing on devices with constraint memory resources.

**Comment by HacknocraftDev** [comment]
This issue was moved to Hacknocraft/AppFriendsAndroidCore#27
