### ISSUE TITLE
Medium: Dialogs List - "first_name" for the last message preview

### ISSUE THREAD

**Issue by hagitmer** [Hacknocraft/AppFriendsAndroidCore#3]
Dialogs List: Last Message Preview: Should have ‘first_name:’ of the user who sent the message before the content of the message. 	

Request: Either add the message sender to the already exposed lastMessage string or add another public variable for "lastMessageSender" and we can format it ourselves.

**Comment by laeroah** [comment]
fixed in version 3.0.5

**Comment by HacknocraftDev** [comment]
This issue was moved to Hacknocraft/AppFriendsAndroidCore#4
