### ISSUE TITLE
Medium: Dialog creation to chat screen transition UX

### ISSUE THREAD

**Issue by hagitmer** [Hacknocraft/AppFriendsAndroidCore#33]
Once the user taps the checkmark icon from the select members screen and navigates to the new message screen to enter a message, the message field should be activated with a cursor, and the keyboard should be up.

**Comment by hagitmer** [comment]
@mikedw was this fixed in the latest SDK merge? Thanks

**Comment by mikedw** [comment]
support for this transition has been added to version 3.1.2

**Comment by hagitmer** [comment]
Thanks @mikedw !

**Comment by HacknocraftDev** [comment]
This issue was moved to Hacknocraft/AppFriendsAndroidCore#33
