### ISSUE TITLE
High: Filtering user names while creating a dialog

### ISSUE THREAD

**Issue by hagitmer** [Hacknocraft/AppFriendsAndroidCore#35]
When a user creates a new dialog and starts typing the names, the list is filtered. However if they select the contact, the typed characters are not cleared and the user ends up with the selected name *and* the typed characters.
The behavior should be that the selected name is replacing the typed characters, similar to how it is in iOS.

**Comment by laeroah** [comment]
@hagitmer Please checkout the latest sample app. We have fixed this a few versions back. The chat settings view is open source, so please take the code from the sample app and update your chat settings activity.

**Comment by hagitmer** [comment]
Thanks @laeroah!

**Comment by HacknocraftDev** [comment]
This issue was moved to Hacknocraft/AppFriendsAndroidCore#35
