### ISSUE TITLE
Urgent: backing out of a 1:1 without sending a message breaks it for life

### ISSUE THREAD

**Issue by hagitmer** [Hacknocraft/AppFriendsAndroidCore#36]
If you create a 1:1 Message, but back out of it before sending any messages, it ends up in a funky state where:
* You cannot send a message
* It shows no title when you open it
* You cannot access the convo settings screen

Verified this happens on AF sample app as well

**Steps to Recreate:**
1. Create a 1:1 conversation
2. Back out before sending a message
3. Go back in
4. Try to send a message
5. Try to access convo settings
6. Look at title field above convo

**Comment by laeroah** [comment]
We can reproduce this issue, and are currently working on a fix. Will update you asap.

**Comment by laeroah** [comment]
@hagitmer hey, we pushed out a fix. Please use version `3.0.13`
The only change in this version comparing to the version you have right now is this fix. Nothing else is included, so you don't have to test everything again.

**Comment by hagitmer** [comment]
Thanks @laeroah

**Comment by HacknocraftDev** [comment]
This issue was moved to Hacknocraft/AppFriendsAndroidCore#36
