### ISSUE TITLE
Low: Leaving the last message in your list does not update the dialog list

### ISSUE THREAD

**Issue by hagitmer** [Hacknocraft/AppFriendsAndroidCore#37]
If a user leaves the last dialog in the list (group or 1-1), the dialog is not cleared. But if the user force closes the app and re-opens it, the user is then correctly in the no messages state. This seems to be caused by a bug where AF doesn't pass the empty dialog list back through the observable we're observing on.

**Comment by mikedw** [comment]
fixed in 3.1.x

**Comment by HacknocraftDev** [comment]
This issue was moved to Hacknocraft/AppFriendsAndroidCore#37
