### ISSUE TITLE
High: can't share photos and videos in dialogs

### ISSUE THREAD

**Issue by hagitmer** [Hacknocraft/AppFriendsAndroidCore#4]
We would like users to be able to share photos and videos into dialogs (group or private).
Doesn't seem to work on the sample app either.

**Comment by hagitmer** [comment]
@laeroah I just tested the new SDK with the media support (3.0.5). It's crashing whenever I try to take a new photo or share from the camera roll.

**Comment by laeroah** [comment]
I think you have the camera permission turned off. We can catch the exception next release but could you try turn the permission on with your phone for now?

**Comment by hagitmer** [comment]
@laeroah I just turned on the the camera permission and it doesn't crash. Can we control the message we provide users when there's no permission?

Also, the resolution is really low, lower than the iOS one. Can that be improved?

**Comment by laeroah** [comment]
Ok, will make the resolution same as iOS as long as the photo source is high-res. And make the messages configurable.

**Comment by hagitmer** [comment]
Thanks @laeroah!

**Comment by hagitmer** [comment]
Hey @laeroah I tried the new SDK; I do get a prompt for granting camera permission however the app still crashes when trying to share from the gallery and I don't grant access to storage.

Also, the resolution seems better when sharing from the gallery (when providing access) however when using the phone camera, it's still very low.

**Comment by hagitmer** [comment]
Hey @laeroah. With the new SDK (3.0.5.5) I'm seeing the following:
- App no longer crashes when permissions are off. Can we control the verbiage for the users prompt?
- Resolution from camera pictures is still very low; however if I share from the gallery, it's high.

**Comment by laeroah** [comment]
you can control the messages. I will put down some doc on how to do it.
Camera and gallery image go through the same compression logic before upload. Could you send me a picture taken by your camera, and then upload a new picture in chat taken from the same camera. Please try take two pictures of the same content.

**Comment by laeroah** [comment]
See `http://appfriends.me/documentation/android/customization/`
Under `String Values` --> `<!-- Permission Checking -->`

**Comment by hagitmer** [comment]
[attachments.zip](https://github.com/Hacknocraft/AppFriendsAndroidCore/files/736325/attachments.zip)

**Comment by laeroah** [comment]
ok, thanks! I think I know what the issue is now. Will fix in next release.

**Comment by HacknocraftDev** [comment]
This issue was moved to Hacknocraft/AppFriendsAndroidCore#5
