### ISSUE TITLE
URGENT: user initials always appear as "LZ"

### ISSUE THREAD

**Issue by hagitmer** [Hacknocraft/AppFriendsAndroidCore#7]
All user initials set to LZ right now. Need to be able to override.  
This is happening in `message_item_them.xml` but we don't seem to have access to this field.

Please expose this field so we can set the initials properly.

**Comment by hagitmer** [comment]
@laeroah this is a blocker for next week's release so will appreciate your input on this. Thanks

**Comment by hagitmer** [comment]
![screenshot_20170123-141156](https://cloud.githubusercontent.com/assets/21039229/22218756/3423cc5a-e176-11e6-89f2-a2c385682720.png)

**Comment by hagitmer** [comment]
@laeroah I noticed that in the recent SDK you've updated the initials however they're still wrong - they now display the first two characters of the user's first name rather than the first character of the first name, and first character of the last name.

**Comment by laeroah** [comment]
Hey, we are just putting a placeholder there same as iOS because we don't have the user real name. Your developer could override the content there like they did for iOS once this version of sdk is released.

**Comment by hagitmer** [comment]
Perfect, thanks @laeroah

**Comment by hagitmer** [comment]
@laeroah when will it be released?

**Comment by HacknocraftDev** [comment]
This issue was moved to Hacknocraft/AppFriendsAndroidCore#8
