### ISSUE TITLE
URGENT: user initials are hard coded to NS in the dialog list

### ISSUE THREAD

**Issue by hagitmer** [Hacknocraft/AppFriendsAndroidCore#8]
Make those configurable.

**Comment by hagitmer** [comment]
![screenshot_20170123-131911](https://cloud.githubusercontent.com/assets/21039229/22218748/2a3d56ac-e176-11e6-8e6f-8cc02d2db05b.png)

**Comment by HacknocraftDev** [comment]
This issue was moved to Hacknocraft/AppFriendsAndroidCore#9
